[platformio]
src_dir = firmware

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/DFRobot/DFRobot_HumanDetection.git
    knolleary/PubSubClient @ ^2.8
extra_scripts = post:start_logger.py