[platformio]
src_dir = firmware
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; This tells VS Code to add timestamps and save everything to a file
monitor_filters = 
    time
    log2file